export const FETCH_RANDOM_USER_SUCCESS = 'FETCH_RANDOM_USER_SUCCESS';
export const FETCH_RANDOM_USER_FAILED = 'FETCH_RANDOM_USER_FAILED';
export const FETCH_RANDOM_USER_PENDING = 'FETCH_RANDOM_USER_PENDING';